import { Event, MachineEventSchema, MachineStateSchema, State } from "./schema.js";
import {
  PersistenceConfig,
  PersistentMachine,
  isPersistentMachine,
} from "./persistence/persistent-machine.js";
import {
  AssertionError,
  DuplicateActorError,
  InvalidSchemaError,
  MissingMatchHandlerError,
  MissingSchemaError,
  ProvisionValidationError,
  SlotProvisionError,
  UnprovidedSlotsError,
} from "./errors.js";
import {
  EffectHandlers,
  EffectSlot,
  EffectSlots,
  EffectsDef,
  EffectsSchema,
  GuardHandlers,
  GuardSlot,
  GuardSlots,
  GuardsDef,
  GuardsSchema,
  MachineContext,
  Slot,
} from "./slot.js";
import {
  PersistentActorRef,
  createPersistentActor,
  restorePersistentActor,
} from "./persistence/persistent-actor.js";
import {
  ActorMetadata,
  PersistedEvent,
  PersistenceAdapter,
  PersistenceAdapterTag,
  PersistenceError,
  RestoreFailure,
  RestoreResult,
  Snapshot,
  VersionConflictError,
} from "./persistence/adapter.js";
import {
  InMemoryPersistenceAdapter,
  makeInMemoryPersistenceAdapter,
} from "./persistence/adapters/in-memory.js";
import "./persistence/index.js";
import {
  BackgroundEffect,
  BuiltMachine,
  HandlerContext,
  Machine,
  MachineRef,
  MakeConfig,
  PersistOptions,
  ProvideHandlers,
  SpawnEffect,
  StateHandlerContext,
  Transition,
  machine_d_exports,
} from "./machine.js";
import { ActorRef, ActorSystem, Default, SystemEvent, SystemEventListener } from "./actor.js";
import {
  SimulationResult,
  TestHarness,
  TestHarnessOptions,
  assertNeverReaches,
  assertPath,
  assertReaches,
  createTestHarness,
  simulate,
} from "./testing.js";
import {
  AnyInspectionEvent,
  EffectEvent,
  ErrorEvent,
  EventReceivedEvent,
  InspectionEvent,
  Inspector,
  SpawnEvent,
  StopEvent,
  TransitionEvent,
  collectingInspector,
  consoleInspector,
  makeInspector,
} from "./inspection.js";
export {
  type ActorMetadata,
  type ActorRef,
  type ActorSystem,
  Default as ActorSystemDefault,
  ActorSystem as ActorSystemService,
  type AnyInspectionEvent,
  AssertionError,
  type BackgroundEffect,
  type BuiltMachine,
  DuplicateActorError,
  type EffectEvent,
  type EffectSlots,
  type EffectsDef,
  type EffectsSchema,
  type ErrorEvent,
  Event,
  type EventReceivedEvent,
  type GuardHandlers,
  type GuardSlot,
  type GuardSlots,
  type GuardsDef,
  type GuardsSchema,
  type HandlerContext,
  InMemoryPersistenceAdapter,
  type InspectionEvent,
  type Inspector,
  Inspector as InspectorService,
  InvalidSchemaError,
  machine_d_exports as Machine,
  type MachineContext,
  type MachineEventSchema,
  type MachineRef,
  type MachineStateSchema,
  type Machine as MachineType,
  type MakeConfig,
  MissingMatchHandlerError,
  MissingSchemaError,
  type PersistOptions,
  type PersistedEvent,
  type PersistenceAdapter,
  PersistenceAdapterTag,
  type PersistenceConfig,
  PersistenceError,
  type PersistentActorRef,
  type PersistentMachine,
  type ProvideHandlers,
  ProvisionValidationError,
  type RestoreFailure,
  type RestoreResult,
  type SimulationResult,
  Slot,
  type EffectHandlers as SlotEffectHandlers,
  type EffectSlot as SlotEffectSlot,
  SlotProvisionError,
  type Snapshot,
  type SpawnEffect,
  type SpawnEvent,
  State,
  type StateHandlerContext,
  type StopEvent,
  type SystemEvent,
  type SystemEventListener,
  type TestHarness,
  type TestHarnessOptions,
  type Transition,
  type TransitionEvent,
  UnprovidedSlotsError,
  VersionConflictError,
  assertNeverReaches,
  assertPath,
  assertReaches,
  collectingInspector,
  consoleInspector,
  createPersistentActor,
  createTestHarness,
  isPersistentMachine,
  makeInMemoryPersistenceAdapter,
  makeInspector,
  restorePersistentActor,
  simulate,
};
